### ISSUE TITLE
value() returns a vector instead of a list

### ISSUE THREAD

**Issue by fangly** [decisionpatterns/r-hash#13]
Hi Christopher,
I have stumbled across a small issue with the hash package:

```
h <- hash(c("a","b","c"), list("bar", 1L, TRUE))
print(h$a); print(h$b); print(h$c)
res <- values(h)
print(class(res)); print(res)
```

As you see, the list of values is stored properly in the hash, but instead of returning a list, values() returns a vector.
Cheers,
Florent

PS/ This is for hash version 2.2.6 (the latest on CRAN)

**Comment by ctbrown** [comment]
I believe you are right. This is a problem.  But the docs show the solution.  By default `values` tries to simplify the response since it raps `sapply`.  Will get the behavior you want.

```
     values( h, simplify=FALSE ) 
```

If there is no objection, I think the best thing to due is either:

- make `simplify=FALSE` the default
- or make `simplify=TRUE` only valid when all the values are of the same class.

Thoughs?

**Comment by fangly** [comment]
You are entirely right, Chris. I must have overlooked the `...` argument passed to `sapply()`, which is a function regarded by some as [potentially dangerous](https://github.com/jimhester/lintr/issues/149).

Personally, I like the principle of least surprise, and would be happy if the return value was always a named list, i.e. have `simplify=FALSE` (or even no "simplify" option).

Here is a suggestion if you want to keep the "simplify" option:
- Use `lapply()` instead of `vapply()`. You get a list "x" back.
- If `simplify=TRUE`, then convert to vector if all keys have the same type using
```R
types <- unique(vapply(x, typeof, character(1L)), nmax=10L)
atomicTypes <- c("logical", "integer", "double", "complex", "character", "raw")
if (length(types) == 1L && types %in% atomicTypes) {
    x <- unlist(x)
}
```

**Comment by ctbrown** [comment]
I am went with always returns a named list. The user can simplify it
themselves with `unlist` if needed.  Thanks for the input.

C-

**Comment by ctbrown** [comment]
This was resolved in 2017.
