### ISSUE TITLE
Wrong value when copying a hash with a single key-value pair

### ISSUE THREAD

**Issue by fangly** [decisionpatterns/r-hash#14]
Hi Chris,

I have discovered a small issue when copying a hash that contains a single key-value pair (in hash version 2.2.6). One receives in the original case a character vector, and in the cloned case something different, a named list (where the name is incorrect):

```R
> h <- hash(1, "a")
> values(h)
  1 
"a" 
> class(values(h))
[1] "character"
> h2 <- copy(h)
> values(h2)
$`1.1`
[1] "a"
> class(values(h2))
[1] "list"
```

To work as intended, the copy method could be rewritten this way:
```R
setMethod( 'copy', 'hash', 
  function(x, ... ) {
      k <- keys(ht)
      v <- mget(k, ht@.xData)
      switch(as.character(length(k)),
        "0" = hash(),
        "1" = hash(k, v[[1]]),
        hash(k, v)
      )
    }
```

Best,

Florent

PS/ I edited ```unlist(v, use.names=FALSE)``` to ```v[[1]]``` which is simpler and more robust when ```v``` contains complex object, e.g. bit64 long integers.

**Comment by ctbrown** [comment]
This does not appear to be a problem with `copy` but a bug in `hash`:

```
> hash( a=1 )$a  %>% class
[1] "list"
```

`a` should not be a list but should be numeric.
