### ISSUE TITLE
Improve Performance by Unsorted return and documentation improvements

### ISSUE THREAD

**Issue by fangly** [decisionpatterns/r-hash#15]
Hi Chris,

I was wondering if the values returned by ```keys()``` and ```values()``` are ordered by time of insertion or in an arbitrary order. I looked at the ```hash``` documentation but found no hint about their order. I then looked at the code and discovered that the order depends on a call to ```ls()```. A quick look at the manpage for ```ls()``` tells me that the output is sorted alphabetically by default (which is what ```keys()``` uses), and that this naturally incurs a time penalty. Thus, I would suggest a few things:

1. hash is performance-oriented. For the sake of performance, add ```sorted=FALSE``` to the ```ls()``` call in the ```keys()``` function. I do not think there would be an overwhelming interest in having the keys sorted alphabetically and those who may need this feature occasionally can still easily do it themselves with a call to ```sort()```.
1. In the documentation for ```keys()```, add that the order of the returned keys is arbitrary.
1. In the documentation for ```values()```, add that the order of the returned values is guaranteed to be the same as keys().

Best,

Florent

PS/ Let me know how I can help further with this.

**Comment by ctbrown** [comment]
This is an compelling suggestion.  I think that a benchmarking is in order especially on larger hashes.  In general, I am amenable to this change.

**Comment by fangly** [comment]
Hi Chris,

Obviously, this issue is not high priority and can wait. However, I saw that you are almost ready for a release and I would **really like** if you could proceed with it, since **the last version of _hash_ on CRAN is very old (version 2.2.6, 2013)** and I am waiting for this to migrate to the 3.x.x series.

When you find the time to integrate my current enhancement request in _hash_, you can use these expectations that will allow the convenient testing of hashes and unsorted (named) lists :
```
setdiff_msg <- function(actual, expected, what="Values") {
  if (is.null(actual)) {
    actual <- list()
  }
  if (is.null(expected)) {
    expected <- list()
  }
  diff <- setdiff(actual, expected)
  if (length(diff)) {
    sprintf("%s not equal. First difference was: %s", what, diff[[1]])
  } else {
    ""
  }
}

expect_sets_equal <- function(actual, expected) {
  names_actual   <- names(actual)
  names_expected <- names(expected)
  if (length(names_actual) || length(names_expected)) {
    # compare set of names, then sorted sequence of corresponding values
    msg <- setdiff_msg(names_actual, names_expected, what="Names")
    expect(!nzchar(msg), msg)
    expect_equal(actual[names_actual], expected[names_actual], info="Values not equal")
  } else {
    # no names present, compare set of values only
    msg <- setdiff_msg(actual, expected)
    expect(!nzchar(msg), msg)
  }
  invisible(actual)
}

expect_hashes_equal <- function(actual, expected) {
  expect_sets_equal(values(actual), values(expected))
  # keys are also tested (present as names in the list reported by values()).
}

h1 <- hash(1:3, 4:6)
h2 <- hash(1:3, c(4,4,6))


expect_sets_equal(keys(h1),keys(h1))
expect_sets_equal(keys(h1),keys(h2))

expect_sets_equal(values(h1),values(h1))
expect_sets_equal(values(h1),values(h2))

expect_hashes_equal(h1, h1)
expect_hashes_equal(h1, h2)
```

Thank you! Best,

Florent

**Comment by fangly** [comment]
Forget what I wrote above, the expect_equal function suffices to compare hashes:
```
h1 <- hash(c(1,2,3), c("a","b","c"))
h2 <- hash(c(3,2,1), c("c","b", "a"))
expect_equal(h1, h2)
```
The reason why this works is that expect_equal ends up calling all.equal.environment, internally.
