### ISSUE TITLE
Could you please push the latest version into CRAN?

### ISSUE THREAD

**Issue by Jiefei-Wang** [decisionpatterns/r-hash#17]
The hash package in CRAN does not import the methods package and therefore the packages reply on hash would get a warning about it from the current package checking procedure. I see the development version has fixed this problem. Since it has been a few years after the last CRAN update, could you post the last stable version into CRAN? Thanks.

**Comment by ctbrown** [comment]
I would love to and have tried; There are some reverse dependencies
failures that have prevented my package from being accepted into CRAN.
Essentially, other package authors have decided to use (improperly)
non-exported methods which cause their tests to fail.  Will try to get to a
resolution in the near future.  Until then `devtools::install_github()` is
your friend.
